version: '3.8'

services:
  nuxt-app:
    image: node:18-alpine
    container_name: nuxt-app
    tty: true
    command: [sh, -c, "yarn install && yarn dev"]
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000